Repository Daniel-Assuncao89/helpr-back-jfs5, pull requests merged in 2022-12, with the labels that each got.

#53 Criacao dependenteDto
  src/main/java/org/soulcodeacademy/helpr/domain/dto/DependenteDTO.java
Labels: enhancement

#54 criado endpoint para extrair lista de chamados em PDF
  pom.xml
  src/main/java/org/soulcodeacademy/helpr/controllers/ChamadoController.java
  src/main/java/org/soulcodeacademy/helpr/domain/ChamadosPDFExporter.java
Labels: enhancement

#55 Tratamento de erro: integridade de dados exception
  src/main/java/org/soulcodeacademy/helpr/controllers/errors/ResourceExceptionHandler.java
Labels: enhancement

#57 Criada entidade de Dependente e Repository
  src/main/java/org/soulcodeacademy/helpr/domain/Dependente.java
  src/main/java/org/soulcodeacademy/helpr/repositories/DependenteRepository.java
  src/main/java/org/soulcodeacademy/helpr/services/PopulateService.java
Labels: enhancement

#58 Atualização do Bcrypt na atualização e salvamento de novo Cliente e F…
  src/main/java/org/soulcodeacademy/helpr/services/ClienteService.java
  src/main/java/org/soulcodeacademy/helpr/services/FuncionarioService.java
Labels: bug

#59 Incremendo to Populate Service, com adição de novos administradores, …
  src/main/java/org/soulcodeacademy/helpr/services/PopulateService.java
Labels: enhancement

#61 Tratamento do service atualizar para preservar cpf e email originais
  src/main/java/org/soulcodeacademy/helpr/services/ClienteService.java
Labels: bug, enhancement

#65 Criação de DTO, service e controller de futuro cliente, correção bugs
  src/main/java/org/soulcodeacademy/helpr/controllers/FuturoClienteController.java
  src/main/java/org/soulcodeacademy/helpr/domain/dto/FuturoClienteDTO.java
  src/main/java/org/soulcodeacademy/helpr/repositories/DependenteRepository.java
  src/main/java/org/soulcodeacademy/helpr/repositories/FuturoClienteRepository.java
  src/main/java/org/soulcodeacademy/helpr/services/FuturoClienteService.java
  src/main/java/org/soulcodeacademy/helpr/services/PopulateService.java
  src/main/java/org/soulcodeacademy/helpr/services/UsuarioService.java
Labels: bug, enhancement

#66 Criado limite de 5 chamados abertos para cada funcionário
  src/main/java/org/soulcodeacademy/helpr/controllers/errors/ResourceExceptionHandler.java
  src/main/java/org/soulcodeacademy/helpr/services/ChamadoService.java
  src/main/java/org/soulcodeacademy/helpr/services/errors/LimiteQuantidadeError.java
Labels: enhancement

#67 Criação de futuro candidato
  src/main/java/org/soulcodeacademy/helpr/controllers/FuturoCandidatoController.java
  src/main/java/org/soulcodeacademy/helpr/domain/FuturoCandidato.java
  src/main/java/org/soulcodeacademy/helpr/domain/dto/FuturoCandidatoDTO.java
  src/main/java/org/soulcodeacademy/helpr/domain/enums/Setor.java
  src/main/java/org/soulcodeacademy/helpr/repositories/FuturoCandidatoRepository.java
  src/main/java/org/soulcodeacademy/helpr/services/FuturoCandidatoService.java
  src/main/java/org/soulcodeacademy/helpr/services/PopulateService.java
Labels: enhancement

#68 Criação de máscara em CPF.
  src/main/java/org/soulcodeacademy/helpr/domain/Usuario.java
  src/main/java/org/soulcodeacademy/helpr/services/PopulateService.java
Labels: enhancement

#69 Método de busca de funcionário por e-mail
  src/main/java/org/soulcodeacademy/helpr/controllers/FuncionarioController.java
  src/main/java/org/soulcodeacademy/helpr/repositories/FuncionarioRepository.java
  src/main/java/org/soulcodeacademy/helpr/services/FuncionarioService.java
Labels: enhancement

#70 Criado endpoint para salvar foto de funcionário no banco de dados
  src/main/java/org/soulcodeacademy/helpr/controllers/FuncionarioController.java
  src/main/java/org/soulcodeacademy/helpr/domain/Funcionario.java
  src/main/java/org/soulcodeacademy/helpr/services/FuncionarioService.java
Labels: enhancement

#71 Criado limite de quantidade de funcionários com o mesmo cargo
  src/main/java/org/soulcodeacademy/helpr/controllers/errors/ResourceExceptionHandler.java
  src/main/java/org/soulcodeacademy/helpr/domain/Cargo.java
  src/main/java/org/soulcodeacademy/helpr/domain/dto/CargoDTO.java
  src/main/java/org/soulcodeacademy/helpr/repositories/FuncionarioRepository.java
  src/main/java/org/soulcodeacademy/helpr/services/CargoService.java
  src/main/java/org/soulcodeacademy/helpr/services/FuncionarioService.java
  src/main/java/org/soulcodeacademy/helpr/services/PopulateService.java
Labels: enhancement

#72 Alterações para funcionar o upload de fotos
  src/main/java/org/soulcodeacademy/helpr/domain/Funcionario.java
  src/main/java/org/soulcodeacademy/helpr/services/FuncionarioService.java
Labels: enhancement

#74 Aplicação do Spring Actuator para gerenciar os endpoints necessários
  pom.xml
  src/main/resources/application-dev.properties
Labels: enhancement

#73 Novo status Arquivado
  src/main/java/org/soulcodeacademy/helpr/controllers/FuncionarioController.java
  src/main/java/org/soulcodeacademy/helpr/domain/enums/StatusChamado.java
  src/main/java/org/soulcodeacademy/helpr/services/ChamadoService.java
Labels: enhancement

#75 Adição dda notação de cpf em futuro cliente
  src/main/java/org/soulcodeacademy/helpr/domain/FuturoCliente.java
Labels: enhancement

#76 criado anotação de proteção de endpoints de acordo com o perfil
  src/main/java/org/soulcodeacademy/helpr/controllers/ChamadoController.java
  src/main/java/org/soulcodeacademy/helpr/controllers/ClienteController.java
  src/main/java/org/soulcodeacademy/helpr/controllers/FuncionarioController.java
Labels: enhancement

#77 Criado endpoints de funcionário, chamado e cargo
  src/main/java/org/soulcodeacademy/helpr/controllers/CargoController.java
  src/main/java/org/soulcodeacademy/helpr/controllers/ChamadoController.java
  src/main/java/org/soulcodeacademy/helpr/controllers/FuncionarioController.java
  src/main/java/org/soulcodeacademy/helpr/repositories/CargoRepository.java
  src/main/java/org/soulcodeacademy/helpr/repositories/ChamadoRepository.java
  src/main/java/org/soulcodeacademy/helpr/repositories/FuncionarioRepository.java
  src/main/java/org/soulcodeacademy/helpr/services/CargoService.java
  src/main/java/org/soulcodeacademy/helpr/services/ChamadoService.java
  src/main/java/org/soulcodeacademy/helpr/services/FuncionarioService.java
Labels: enhancement

#78 Criacao de procedure que lista chamados abertos hoje
  SQL script/proc_lista_chamado_aberto_hoje.sql
Labels: enhancement
